# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

"""`idp-feature-cli` — command-line entry point for the feature publisher."""

from __future__ import annotations

import sys
from importlib.resources import files
from pathlib import Path
from typing import Optional

import click
from rich.console import Console

from .manifest import ManifestError, load_manifest
from .publisher import FeaturePublisher
from .scaffold import ScaffoldError, ScaffoldOptions, scaffold_feature

console = Console()


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(package_name="idp-feature-sdk")
def main() -> None:
    """Publish IDP Accelerator feature packages to a Marketplace-style S3 bucket."""


@main.command()
@click.argument(
    "project_dir", type=click.Path(exists=True, file_okay=False, path_type=Path)
)
def validate(project_dir: Path) -> None:
    """Validate <PROJECT_DIR>/feature.yaml against the schema and linked files."""
    try:
        manifest = load_manifest(project_dir)
    except ManifestError as exc:
        console.print(f"[red]✗ {exc}[/red]")
        sys.exit(1)
    console.print(
        f"[green]✓[/green] [bold]{manifest.featureId}[/bold] v{manifest.version} — "
        f"{manifest.displayName}"
    )
    if manifest.marketplace.productCode:
        console.print(f"  Marketplace productCode: {manifest.marketplace.productCode}")
    if manifest.capabilities:
        console.print(f"  capabilities: {', '.join(manifest.capabilities)}")


@main.command()
@click.argument(
    "project_dir", type=click.Path(exists=True, file_okay=False, path_type=Path)
)
def build(project_dir: Path) -> None:
    """Build the UI bundle and run static validation. No uploads."""
    try:
        publisher = FeaturePublisher(project_dir, console=console)
        publisher.build()
    except (ManifestError, RuntimeError, ValueError) as exc:
        console.print(f"[red]✗ {exc}[/red]")
        sys.exit(1)


@main.command()
@click.argument(
    "project_dir", type=click.Path(exists=True, file_okay=False, path_type=Path)
)
@click.option(
    "--seller-bucket", required=True, help="S3 bucket to upload artifacts to."
)
@click.option("--region", default="us-east-1", show_default=True)
@click.option("--prefix", "s3_prefix", default="features", show_default=True)
@click.option(
    "--make-public",
    is_flag=True,
    default=False,
    help="Upload objects with ACL=public-read. Required for Launch Stack URLs to "
    "work without additional bucket policy. Your seller bucket's ACL settings "
    "must permit this.",
)
@click.option(
    "--register-with-simulator",
    default=None,
    help="Also POST a CreateProduct call to the marketplace-simulator at this URL, "
    "so the feature flows through GetEntitlements locally. e.g. http://127.0.0.1:8080",
)
@click.option(
    "--simulator-product-code",
    default=None,
    help="productCode to register with the simulator. Defaults to 'prod-<featureId>'.",
)
def publish(
    project_dir: Path,
    seller_bucket: str,
    region: str,
    s3_prefix: str,
    make_public: bool,
    register_with_simulator: Optional[str],
    simulator_product_code: Optional[str],
) -> None:
    """Validate → build → upload → update latest.json. Prints a Launch Stack URL on success."""
    try:
        publisher = FeaturePublisher(project_dir, console=console)
        result = publisher.publish(
            seller_bucket=seller_bucket,
            region=region,
            s3_prefix=s3_prefix,
            make_public=make_public,
            register_with_simulator=register_with_simulator,
            simulator_product_code=simulator_product_code,
        )
    except (ManifestError, RuntimeError, ValueError) as exc:
        console.print(f"[red]✗ {exc}[/red]")
        sys.exit(1)

    console.print()
    console.rule("[bold]Published[/bold]")
    console.print(f"  featureId:      {result.feature_id}")
    console.print(f"  version:        {result.version}")
    console.print(f"  template:       {result.template_url}")
    console.print(f"  ui bundle:      {result.bundle_url}")
    console.print(f"  manifest:       {result.manifest_url}")
    console.print(f"  latest.json:    {result.latest_json_url}")
    console.print()
    console.print("[bold]🚀 Launch Stack URL (placeholder MAINSTACKNAME):[/bold]")
    console.print(f"  {result.launch_url}")
    console.print()
    console.print(
        "[dim]In production this URL is generated by the main stack's "
        "getFeatureLaunchUrl resolver, which substitutes the real MainStackName and "
        "gates on the caller's Admin role.[/dim]"
    )


@main.command("show-schema")
def show_schema() -> None:
    """Print the feature.yaml JSON schema to stdout."""
    schema_path = files("idp_feature_sdk.schemas").joinpath(
        "feature-manifest.schema.json"
    )
    print(schema_path.read_text(encoding="utf-8"))


@main.command("init")
@click.argument("project_dir", type=click.Path(file_okay=False, path_type=Path))
@click.option(
    "--feature-id",
    required=True,
    help="DNS-safe slug, e.g. 'docs-by-status'. Used as the S3 prefix, "
    "Cognito session-tag value, and `window.IdpFeatures.register()` key.",
)
@click.option(
    "--display-name",
    required=True,
    help="Human-readable name shown in the IDP nav and on the feature page, "
    "e.g. 'Docs By Status'.",
)
@click.option(
    "--version",
    "version",
    default="0.1.0",
    show_default=True,
    help="Initial SemVer for the feature.",
)
def init_cmd(
    project_dir: Path, feature_id: str, display_name: str, version: str
) -> None:
    """Scaffold a new feature project from the bundled feature-template/.

    Copies the template into <PROJECT_DIR> and substitutes the placeholder
    featureId / displayName / version literals throughout (feature.yaml,
    template.yaml, package.json, entry.tsx, App.tsx, handler.py, README.md).
    Skips node_modules/, dist/, __pycache__/. Refuses to overwrite an
    existing directory.
    """
    try:
        created = scaffold_feature(
            ScaffoldOptions(
                project_dir=project_dir,
                feature_id=feature_id,
                display_name=display_name,
                version=version,
            )
        )
    except ScaffoldError as exc:
        console.print(f"[red]✗ {exc}[/red]")
        sys.exit(1)

    console.print(
        f"[green]✓[/green] Scaffolded [bold]{feature_id}[/bold] v{version} → {created}"
    )
    console.print()
    console.print("  Next steps:")
    console.print(f"    cd {created}")
    console.print(
        "    # customise feature-api/handler.py, feature-ui/src/App.tsx, template.yaml"
    )
    console.print("    cd feature-ui && npm install && cd ..")
    console.print("    idp-feature-cli validate .")
    console.print("    idp-feature-cli build .")
    console.print("    idp-feature-cli publish . --seller-bucket <bucket>")


if __name__ == "__main__":
    main()
