query ListDocuments($startDateTime: AWSDateTime, $endDateTime: AWSDateTime, $limit: Int, $nextToken: String, $submissionSource: String) {
  listDocuments(startDateTime: $startDateTime, endDateTime: $endDateTime, limit: $limit, nextToken: $nextToken, submissionSource: $submissionSource) {
    Documents {
      PK
      SK
      ObjectKey
      ObjectStatus
      InitialEventTime
      CompletionTime
      ConfigVersion
      EvaluationStatus
      HITLStatus
      HITLTriggered
      HITLCompleted
      HITLReviewOwner
      HITLReviewedBy
      PageCount
      ConfidenceAlertCount
      ProcessingIssueCount
    }
    nextToken
  }
}
